image: docker/compose:debian-1.29.2

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cp $DOT_ENV $(pwd)/.env
  - export $( grep -vE "^(#.*|\s*)$" .env )
  - IMAGE_NAME=$CI_REGISTRY/$ORGANIZATION/$PATH_TO_PROJECT:$CI_ENVIRONMENT_SLUG-$CI_COMMIT_SHA
  - echo $IMAGE_NAME


build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  tags:
    - job:build
  only:
    - master
  environment:
    name: prod

test:
  stage: test
  script:
    - docker pull $IMAGE_NAME
    - docker-compose --profile test up -d
    - docker-compose exec -T app-server npm run test
  tags:
    - job:test
  only:
    - master
  environment:
    name: prod

deploy:
  stage: deploy
  script:
    - docker pull $IMAGE NAME
    - docker-compose --profile prod down
    - docker-compose --profile prod up
  tags:
    - job:deploy
  only:
    - master
  environment:
    name: prod
  when: manual